### ISSUE TITLE
ORA grading not displaying ORAs with file uploads

### ISSUE THREAD

**Issue by FatemeKhodayari** [openedx/frontend-app-ora-grading#285]
### Bug Description
Hi. I'm running openedx palm 3 with tutor. Recently I found that when trying to open an ORA with file upload by clicking on the "View all responses" button, the frontend crashes, displaying the page below:

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/b1835e8c-272e-4964-b4e2-c5e0dc32083d)

When using a low speed internet connection, you can get a glance of the ORA app but then the said page will be displayed within a second. Diving more into the issue, I realised that the actual error is coming from the file preview part and then later when trying to show the error banner, another error occurs which is what we see in the screenshot above.

### How to reproduce
1. On a palm 3 installation of openedx, head to studio. Create an open response unit with optional or required file upload.
To do so, create a course and then a section and subsection. Within the subsection create a unit and choose "Open Response" component.

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/853c38c3-5994-4d54-b887-4a19d2d8b6d7)

Choose one of the types (I chose staff review assessment). Then click on the "Edit" button on top of the component. 

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/d8d0215c-b0b1-4b7f-af51-5ceb19dee78d)

Then on the "Settings" tab, enable file upload by making it either "Required" or "Optional".

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/72a6b235-864d-43f8-b258-96696e0e4477)

2. Save and publish your changes. Head to LMS by clicking on "View live version" button. Add your response and a file 
to the ORA. Upload the file and submit the ORA. 

3. Now for grading, with a staff access, click on the "Grade available responses" button at the bottom of the unit.

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/bfeac8fc-e210-42d2-9f4b-ee8acc897c73)

4. In the opened page click on the "View all responses" button on top right to get the error page.

![image](https://github.com/openedx/frontend-app-ora-grading/assets/55655542/aad1ed5a-c61c-4d9c-9d95-9ac1dcffbbc6)

### Environment 
OpenedX Palm 3
Tutor 16.1.5
Ubuntu 22.04

### Additional context
The issue was originally [posted on openedx forum](https://discuss.openedx.org/t/ora-grading-returns-error/11482).

**Comment by CodeWithEmad** [comment]
@FatemeKhodayari I close this one since it was resolved.
