### ISSUE TITLE
Node 20 upgrade

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-ora-grading#319]
### Description

See the parent ticket for the general description and motivation, https://github.com/openedx/public-engineering/issues/267.  Make sure to follow its recommendations for each step of the process.

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/348
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/349
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/365
```

**Comment by Anas12091101** [comment]
@arbrandes I'd like to take up this issue on behalf of my team at MIT. Would that be okay?

**Comment by brian-smith-tcril** [comment]
@Anas12091101 thank you so much! Please do!
